:seedling: Add format and test

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -29,3 +29,14 @@ jobs:
         uses: golangci/golangci-lint-action@v3
         with:
           version: latest
+      - name: format
+        run: |
+          make format
+          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
+            echo "All files formatted"
+          else
+            echo "Running format is required"
+            exit 1
+          fi
+      - name: test
+        run: make test
